import type { Metadata } from "next";
import { Commissioner } from "next/font/google";

import "./globals.css";

const commissioner = Commissioner({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Creative App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${commissioner.variable} mx-auto w-full max-w-7xl antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
